services:
  db:
    image: docker.io/postgres:17-alpine
    restart: always
    environment:
      POSTGRES_DB: "dotabot"
      POSTGRES_PASSWORD: "p4ssw0rd"
      POSTGRES_USER: "admin"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    command: postgres -c log_connections=on -c log_hostname=on -c log_statement=all -c log_line_prefix="%m [%p] %u@%d "
        
  adminer:
    image: docker.io/adminer:latest
    restart: always
    ports:
      - "8080:8080"

  redis:
    image: docker.io/redis:8.6-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata: