version: "1"
projects:
  - name: DotaBot
    environments:
      - name: Staging
        services:
          - type: worker
            name: dotabot-discord
            runtime: docker
            repo: https://github.com/Flusaka/dotabot.js
            plan: starter
            envVars:
              - key: DATABASE_URL
                fromDatabase:
                  name: dotabot-pg
                  property: connectionString
              - key: NOTIFICATION_DATABASE_HOST
                fromService:
                  name: dotabot-redis
                  type: keyvalue
                  property: host
              - key: NOTIFICATION_DATABASE_PORT
                fromService:
                  name: dotabot-redis
                  type: keyvalue
                  property: port
              - key: DISCORD_TOKEN
                sync: false
            region: frankfurt
            dockerContext: .
            dockerfilePath: ./apps/discord/Dockerfile
            autoDeployTrigger: checksPass
            branch: feature/deployment
            preDeployCommand: "bun run db:migrate"
          - type: worker
            name: dotabot-sync
            runtime: docker
            repo: https://github.com/Flusaka/dotabot.js
            plan: starter
            envVars:
              - key: DATABASE_URL
                fromDatabase:
                  name: dotabot-pg
                  property: connectionString
              - key: PANDASCORE_TOKEN
                sync: false
            region: frankfurt
            dockerContext: .
            dockerfilePath: ./apps/sync/Dockerfile
            autoDeployTrigger: checksPass
            branch: feature/deployment
          - type: keyvalue
            name: dotabot-redis
            ipAllowList: []
            region: frankfurt
            plan: free
        databases:
          - name: dotabot-pg
            databaseName: dotabot
            user: dotabot_user
            plan: free
            region: frankfurt
            postgresMajorVersion: "18"
            # diskSizeGB: 1
            ipAllowList: []
            